export const ScreenerOrder = {
    TICKER: 'ticker',
    TICKERS_FILTER: 'tickersfilter',
    COMPANY: 'company',
    SECTOR: 'sector',
    INDUSTRY: 'industry',
    COUNTRY: 'country',
    INDEX: 'index',
    EXCHANGE: 'exchange',
    MARKET_CAP: 'marketcap',
    PRICE_EARNINGS:'pe',
    FORWARD_PRICE_EARNINGS: 'forwardpe',
    PEG_PRICE_EARNINGS_GROWTH: 'peg',
    PRICE_SALES:'ps',
    PRICE_BOOK:'pb',
    PRICE_CASH:'pc',
    PRICE_FREE_CASH_FLOW:'pfcf',
    DIVIDEND_YIELD:'dividendyield',
    PAYOUT_RATIO:'payoutratio',
    EPS_TTM:'eps',
    EPS_ESTIMATE_NEXT_QUARTER: 'estq1',
    EPS_GROWTH_THIS_YEAR:'epsyoy',
    EPS_GROWTH_NEXT_YEAR:'epsyoy1',
    EPS_GROWTH_PAST_THREE_YEARS:'eps3years',
    EPS_GROWTH_PAST_FIVE_YEARS:'eps5years',
    EPS_GROWTH_NEXT_FIVE_YEARS:'estltgrowth',
    EPS_GROWTH_QTR_OVER_QTR:'epsqoq',
    EPS_YEAR_OVER_YEAR_TTM:'epsyoyttm',
    SALES_GROWTH_PAST_THREE_YEARS:'sales3years',
    SALES_GROWTH_PAST_FIVE_YEARS:'sales5years',
    SALES_GROWTH_QTR_OVER_QTR:'salesqoq',
    SALES_YEAR_OVER_YEAR_TTM:'salesyoyttm',
    EPS_SURPRISE:'epssurprise',
    REVENUE_SURPRISE:'revenuesurprise',
    SHARES_OUTSTANDING:'sharesoutstanding2',
    SHARES_FLOAT:'sharesfloat',
    FLOAT_OUTSTANDING_PERCENT:'floatoutstandingpct',
    INSIDER_OWNERSHIP:'insiderown',
    INSIDER_TRANSACTIONS:'insidertrans',
    INSTITUTIONAL_OWNERSHIP:'instown',
    INSTITUTIONAL_TRANSACTIONS:'insttrans',
    SHORT_INTEREST_SHARE:'shortinterestshare',
    SHORT_INTEREST_RATIO:'shortinterestratio',
    SHORT_INTEREST:'shortinterest',
    EARNINGS_DATE:'earningsdate',
    LATEST_NEWS_DATE:'news_date',
    RETURN_ON_ASSETS:'roa',
    RETURN_ON_EQUITY:'roe',
    RETURN_ON_INVESTED_CAPITAL:'roi',
    CURRENT_RATIO:'curratio',
    QUICK_RATIO:'quickratio',
    LT_DEBT_EQUITY:'ltdebteq',
    TOTAL_DEBT_EQUITY:'debteq',
    GROSS_MARGIN:'grossmargin',
    OPERATING_MARGIN:'opermargin',
    NET_PROFIT_MARGIN:'netmargin',
    ANALYST_RECOMMENDATION:'recom',
    PERFORMANCE_WEEK:'perf1w',
    PERFORMANCE_MONTH:'perf4w',
    PERFORMANCE_QUARTER:'perf13w',
    PERFORMANCE_HALF_YEAR:'perf26w',
    PERFORMANCE_YEAR_TO_DATE:'perfytd',
    PERFORMANCE_YEAR:'perf52w',
    PERFORMANCE_THREE_YEARS:'perf3y',
    PERFORMANCE_FIVE_YEARS:'perf5y',
    PERFORMANCE_TEN_YEARS:'perf10y',
    BETA:'beta',
    AVERAGE_TRUE_RANGE:'averagetruerange',
    VOLATILITY_WEEK:'volatility1w',
    VOLATILITY_MONTH:'volatility4w',
    TWENTY_DAY_SMA_RELATIVE:'sma20',
    FIFTY_DAY_SMA_RELATIVE:'sma50',
    TWO_HUNDRED_DAY_SMA_RELATIVE:'sma200',
    FIFTY_DAY_HIGH_RELATIVE:'high50d',
    FIFTY_DAY_LOW_RELATIVE:'low50d',
    FIFTY_TWO_WEEK_HIGH_RELATIVE:'high52w',
    FIFTY_TWO_WEEK_LOW_RELATIVE:'low52w',
    FIFTY_TWO_WEEK_RANGE:'52wrange',
    ALL_TIME_HIGH_RELATIVE:'highat',
    ALL_TIME_LOW_RELATIVE:'lowat',
    RELATIVE_STRENGTH_INDEX_FOURTEEN:'rsi',
    AVERAGE_VOLUME:'averagevolume',
    RELATIVE_VOLUME:'relativevolume',
    CHANGE:'change',
    CHANGE_FROM_OPEN:'changeopen',
    GAP:'gap',
    VOLUME:'volume',
    OPEN:'open',
    HIGH:'high',
    LOW:'low',
    PRICE:'price',
    PREVIOUS_CLOSE:'prevclose',
    TARGET_PRICE:'targetprice',
    IPO_DATE:'ipodate',
    BOOK:'book',
    CASH_PER_SHARE:'cashpershare',
    DIVIDEND:'dividend',
    DIVIDEND_EX_DATE:'dividendexdate',
    DIVIDEND_TTM:'dividendttm',
    DIVIDEND_GROWTH_ONE_YEAR:'dividend1y',
    DIVIDEND_GROWTH_THREE_YEARS:'dividend3y',
    DIVIDEND_GROWTH_FIVE_YEARS:'dividend5y',
    EMPLOYEES:'employees',
    INCOME:'income',
    SALES:'sales',
    ENTERPRISE_VALUE:'enterpriseValue',
    EVEBITDA:'evebitda',
    EV_SALES:'evsales',
    OPTIONABLE:'optionable',
    SHORTABLE:'shortable',
    NEWS_URL:'newsurl',
    NEWS_TITLE:'newstitle',
    NEWS_TIME:'newstime',
    DAILY_DIGEST:'wiimdailydigest',
    ETF_SINGLE_CATEGORY:'e.category',
    ETF_TAGS:'e.tags',
    ETF_TOTAL_HOLDINGS:'e.totalholdings',
    ETF_ASSETS_UNDER_MANAGEMENT:'e.assetsundermanagement',
    ETF_NET_FUND_FLOWS_ONE_MONTH:'e.netflows1month',
    ETF_NET_FUND_FLOWS_PERCENT_ONE_MONTH:'e.netflows1monthpct',
    ETF_NET_FUND_FLOWS_THREE_MONTHS:'e.netflows3month',
    ETF_NET_FUND_FLOWS_PERCENT_THREE_MONTHS:'e.netflows3monthpct',
    ETF_NET_FUND_FLOWS_YTD:'e.netflowsytd',
    ETF_NET_FUND_FLOWS_PERCENT_YTD:'e.netflowsytdpct',
    ETF_ANNUALIZED_RETURN_ONE_YEAR:'e.return1year',
    ETF_ANNUALIZED_RETURN_THREE_YEARS:'e.return3year',
    ETF_ANNUALIZED_RETURN_FIVE_YEARS:'e.return5year',
    ETF_NET_EXPENSE_RATIO:'e.netexpenseratio',
    ETF_ACTIVE_PASSIVE:'e.activepassive',
    ETF_ASSET_TYPE:'e.assettype',
    ETF_TYPE:'e.etftype',
    ETF_SECTOR_THEME:'e.sectortheme',
} as const;

/** Union of all known screener field ID values. */
export type ScreenerOrder = (typeof ScreenerOrder)[keyof typeof ScreenerOrder];
